cards = [
    {
        id: "Lunar Blessing",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nAdd 3 intensity.",
    },
    {
        id: "Zolar Blessing",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nAdd 1 intensity to all your cards in your hand.\nReduce the mana cost of all cards in your hand by 1.",
    },
    {
        id: "Zpell Cascade",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\nGain 2 zpell crystals.\nAdd 2 mana if you control the most zummons.",
    },
    {
        id: "Fang Stalker",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[15 seconds] Deal 2 damage.\n[Fang Stalker Damage] Reclaim a random card.",
    },
    {
        id: "Void Zifter",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter] Intensity 1: Reclaim a random card.",
    },
    {
        id: "Reunion",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Zummon Cast] Gain a mana crystal.",
    },
    {
        id: "Zummer Chorus",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Zummon Cast] Gain a zpell crystal.",
    },
    {
        id: "Bird Zong",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nGain 10% mana regen.\nWhen you cast a zpell with mana cost 6 or greater, reclaim Bird Song.",
    },
    {
        id: "Zoul Ziphon",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enemy Zpell Cast] Gain a mana crystal.",
    },
    {
        id: "Overgrowth",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter] For each enemy, dispel a random card.",
    },
    {
        id: "Aria of the Ancients",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Enter] Draw a card.\n[Your Enchantment Cast] Draw a card.",
    },
    {
        id: "Eyes of the Forest",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Your Zummon Damage] Draw a card.",
    },
    {
        id: "Blood for Blood",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zacrifice] Deal 1 damage to each enemy and gain 1 life.",
    },
    {
        id: "Profane Ritual",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Your Zacrifice] Draw a card and lose 2 life.",
    },
    {
        id: "Woodland Stomper",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[10 seconds] Intensity 2: Deal 2 damage.",
    },
    {
        id: "Wildwood Elemental",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[10 seconds] Intensity 1: Deal 2 damage to each enemy.",
    },
    {
        id: "Primal Behemoth",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[10 seconds] Deal 4 damage.\n[Primal Behemoth Damage] Draw a card and gain 2 mana.",
    },
    {
        id: "Avatar of Life",
        manaCost: 8,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[10 seconds] Deal 6 damage.\n[Avatar of Life Damage] Reduce the mana cost of a random card in your hand to 0.",
    },
    {
        id: "Ritual of Renewal",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Your Zummon is Dispelled or Buried] Draw a card.",
    },
    {
        id: "Ztampede",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Your Zummon Cast] Add 1 intensity to Ztampede.\n[Your Zummon Cast] Intensity 2: Deal 1 damage.",
    },
    {
        id: "Wolf Pack",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Deal 1 damage to each enemy for each zummon in your arena.",
    },
    {
        id: "Animal Companions",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Draw a card for each druid zummon in your arena.\n[10 seconds] Deal 1 damage.",
    },
    {
        id: "Zong of Creation",
        manaCost: 4,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Enchantment\n\n\n[Your Zummon is Dispelled] Gain a Nature's Blessing.",
    },
    {
        id: "Bear Companion",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\nYour mana regen is increased by 20%.\n[10 Seconds] Deal 1 damage to each enemy.",
    },
    {
        id: "Wandering Druid",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[10 Seconds] Deal 1 damage.\n[Enter] Gain a Bear Companion",
    },
    {
        id: "Treefolk Elder",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[10 seconds] Deal 4 damage.\n[Enter or Treefolk Elder Damage] Gain 20% mana regen.",
    },
    {
        id: "Progenitor",
        manaCost: 10,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[10 seconds] Deal 7 damage.\n[Damage] Gain a mana crystal for each damage dealt.",
    },
    {
        id: "Mind Reading",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment - Curse\n\n\n[Cursed Enemy Draw] Draw a card.",
    },
    {
        id: "Hungry Zlime",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Dispel an aura or enchantment and gain life equal to its mana cost.",
    },
    {
        id: "Pull from the Ether",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nDraw an enchantment card.",
    },
    {
        id: "Giant Zummoning",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDraw a zummon card with mana cost 6 or greater.",
    },
    {
        id: "Zow the Land",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\nConsume all of your mana and gain 10% mana regen for each mana consumed.",
    },
    {
        id: "Circle of Life",
        manaCost: 1,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nZacrifice a zummon and draw cards equal to its mana cost.",
    },
    {
        id: "Food Chain",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n2 charges.\nZacrifice a zummon and gain a random zummon from your deck with a higher mana cost.",
    },
    {
        id: "Zeason of Growth",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\nEach enemy gains 10% mana regen.\nGain 40% mana regen.",
    },
    {
        id: "Life Force",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nDraw a card for each zummon in your arena and gain life equal to their mana costs.",
    },
    {
        id: "Wild Zummoning",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDraw 2 zummon cards.\nReduce the mana cost of your next zummon zpell by 6.",
    },
    {
        id: "Birthing Pool",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n\nZummons cost 1 less to cast.",
    },
    {
        id: "Everglades",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Enchantment\n\n[Your Zummon Cast] Reduce the mana cost of your next enchantment zpell to 0.",
    },
    {
        id: "Nature's Revenge",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Your Zummon is Dispelled] Gain two random zummons from your deck and zacrifice Nature's Revenge.",
    },
    {
        id: "Zpring Bloom",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n\nGain 20% mana regen.",
    },
    {
        id: "Forest Dryad",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\n[10 seconds] Gain 1 mana.",
    },
    {
        id: "Harvest",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\n\nGain 3 mana crystals.",
    },
    {
        id: "Midsummer Festival",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Enchantment\n\n\n[10 seconds] Gain 1 mana for each zpell class in your arena.",
    },
    {
        id: "Insatiable Zapling",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\n\n\n[Enter] Dispel an aura or enchantment.",
    },
    {
        id: "Mana Zurge",
        manaCost: 0,
        archetypes: [],
        tags: [],
        debugText: "Charm\n\n\n\nGain 2 mana.",
    },
    {
        id: "The World Tree",
        manaCost: 10,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\n\n\nYour mana gain is tripled.",
    },
    {
        id: "Nature's Blessing",
        manaCost: 3,
        archetypes: [],
        tags: [],
        debugText: "Enchantment\n\n\nYour mana regen is increased by 30%.",
    },
    {
        id: "Eternity",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Aura\n\n\nYour zummons do not expire.\n[10 seconds] Lose 1 mana.",
    },
    {
        id: "Counterzpell",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\n\nCounter a zpell.",
    },
    {
        id: "Epiphany",
        manaCost: 4,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n\nDraw 3 cards.",
    },
    {
        id: "Will-o'-Wisp",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\nEnter: Banish an enchantment or zummon to the top of its owner's deck.",
    },
    {
        id: "Inspiration",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\n\n\n\n[Enemy Draw] Draw a card.",
    },
    {
        id: "Deja Vu",
        manaCost: 5,
        archetypes: [],
        tags: [],
        debugText: "Enchantment\n\n\n\nYour triggers are doubled.",
    },
    {
        id: "Poke and Prod",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDeal 1 damage.\n3 Charges.",
    },
    {
        id: "Zcorched Earth",
        manaCost: 10,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\n\n\nYour damage dealt is tripled.",
    },
    {
        id: "Zpellstone",
        manaCost: 3,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\n\nYour charms and zorceries deal 1 extra damage.",
    },
    {
        id: "Flame Zpirit",
        manaCost: 3,
        archetypes: [13, 14, 15],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Zpell Cast] Deal 1 damage.",
    },
    {
        id: "Reflection",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n\nCopy a zummon.",
    },
    {
        id: "Fae Mischief",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nEnter: Take control of an enchantment or zummon.",
    },
    {
        id: "Evil Twin",
        manaCost: 5,
        archetypes: [],
        tags: [],
        debugText: "Zorcery\n\n\n\nDispel a zummon and copy it.",
    },
    {
        id: "Zpellsteal",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\n\nCounter a zpell, then reclaim it.",
    },
    {
        id: "Forbidden Rites",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nResurrect an enchantment or zummon.",
    },
    {
        id: "Traumatic End",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\nDispel a zummon and each player buries 3 cards.",
    },
    {
        id: "Grave Echoes",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zummon Exits] Deal 1 damage to each enemy and you gain 1 life.",
    },
    {
        id: "Drain Life",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\nDispel a zummon and gain life crystals equal to its mana cost.",
    },
    {
        id: "Fiery Zpirit",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zpell Cast] Add 1 intensity to all cards in your hand.",
    },
    {
        id: "Wild Growth",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[10 seconds] Gain 1 mana.\nYou may cast this card from the void.",
    },
    {
        id: "Zpirit of the Woods",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[10 seconds] Intensity 1: Gain 1 Mana.",
    },
    {
        id: "Mystic Glade",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] Your mana regen is increased by 15% for each enchantment in your arena.",
    },
    {
        id: "Mana Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\nZacrifice to gain 1 mana.",
    },
    {
        id: "Life Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\nZacrifice to gain 2 life.",
    },
    {
        id: "Zpell Crystal",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\nZacrifice to draw a card.",
    },
    {
        id: "Blood Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\nZacrifice to deal 1 damage to each enemy.",
    },
    {
        id: "Berserker Chieftain",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[10 seconds] Add 1 intensity to all zummons in your arena.\n[10 seconds] Intensity 1: Deal 1 damage.",
    },
    {
        id: "Jack of All Trades",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Aura\n\nZpells you cast are every zpell class.\n[10 seconds] Lose 1 mana.",
    },
    {
        id: "Void Zalvager",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\n\n\n\n[Enter] Reclaim a card.",
    },
    {
        id: "Chaining Ztorm",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zpell Cast] Add 1 intensity to all cards in your arena.",
    },
    {
        id: "Enchantress",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Draw a random enchantment card from your deck.",
    },
    {
        id: "Call of the Abyss",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[30 seconds] Reclaim a random zummon.",
    },
];
cardIds = cards.map(card => card.id);
cardsById = cards.reduce(
    (dictionary, card) => {
        dictionary[card.id] = card;
        return dictionary;
    }, {}
);