cards = [
    {
        id: "Dream Thief",
        manaCost: 7,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Aura\n\n[30 seconds] Draw a card from each enemy's library.\nChannel 1.",
    },
    {
        id: "Raise Dead",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Aura\n[30 seconds] Resurrect a random enchantment or zummon.\nChannel 1.",
    },
    {
        id: "Cycle of Rebirth",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\nDispel a zummon and gain 10% mana regen.",
    },
    {
        id: "Ztun",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nEnemy enchantments and zummons cannot trigger for 10 seconds.",
    },
    {
        id: "Frenzied Digging",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDispel a zummon.\nDiscard a random card and draw a card.",
    },
    {
        id: "Enchanted Presence",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n2 charges.\nDraw an aura.",
    },
    {
        id: "All for One",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\nResurrect a zummon.\nYou may zacrifice 2 random zummons to reclaim All for One.",
    },
    {
        id: "Mind Flay",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nEach enemy discards a random card and you draw 3 cards.",
    },
    {
        id: "Ztrangulate",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nDeal damage equal to the number of zummons in the void to each enemy.",
    },
    {
        id: "Miracle",
        manaCost: 10,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\nResurrect all enchantments and zummons.",
    },
    {
        id: "Dread Zummons",
        manaCost: 10,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nEach player buries 5 cards, then resurrect all zummons buried this way.",
    },
    {
        id: "Unstable Rift",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n2 charges.\nGain a random zummon.",
    },
    {
        id: "Polymorph",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nA zummon becomes a random zummon.",
    },
    {
        id: "Chaotic Rift",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\nConsume 2: Gain a random zummon.",
    },
    {
        id: "Clone",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\nDiscard a card.\nCopy an enchantment or zummon.",
    },
    {
        id: "Golden Goose",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter] Exchange control of Golden Goose and another enchantment or zummon.\n[Defend] Gain 1 life.",
    },
    {
        id: "Ztalwart Defender",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\n[Defend] Gain a zhield.",
    },
    {
        id: "Ztubbornness",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\nZhield 1.\nZacrifice Ztubbornness: Counter all zpells.",
    },
    {
        id: "Cutpurse",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Attack] Draw a card and discard it after 10 seconds.",
    },
    {
        id: "Footpad",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Draw a card and discard it after 10 seconds.\n[Attack] Deal 2 damage.",
    },
    {
        id: "Quicktrigger",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nTrigger an enchantment or zummon.",
    },
    {
        id: "Double Dip",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nTrigger an enchantment or zummon twice.",
    },
    {
        id: "Drill Zergeant",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n[Enter] Trigger an enchantment or zummon.\n[Attack] Deal 1 damage.",
    },
    {
        id: "Energy Flux",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Charm\n\n[10 seconds] Lose 1 mana.\n[30 seconds] Trigger all your enchantments or zummons.",
    },
    {
        id: "Keeper of Zcrolls",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Zummon\n\n[Attack] Draw a card.\n[30 seconds] Your zummon triggers are doubled.",
    },
    {
        id: "Barrier",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nTrigger and enchantment or zummon and it gains a zhield.",
    },
    {
        id: "Abjurer",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n[Enter and Defend]: Gain a Zhield.",
    },
    {
        id: "Initiate",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\nIntensity: 2\n[Enemy Zpell Cast]: Draw a card if the zpell's mana cost is less than Initiate's intensity.",
    },
    {
        id: "Apprentice",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\n[Enter]: Reclaim a charm.",
    },
    {
        id: "Flash Zlinger",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\nFlash Zlinger resolves instantly.\n[Enter]: Reclaim a zpell. Your next zpell resolves instantly.",
    },
    {
        id: "Banisher",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter] Banish an enchantment or zummon to its owner's hand.\n[Defend] Gain 2 life.",
    },
    {
        id: "Alter Reality",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nBanish an enchantment or zummon to the bottom of its owner's deck.",
    },
    {
        id: "Archmage",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Charm or Zorcery Cast] Gain a zpell crystal.",
    },
    {
        id: "Illusionist",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Your Charm or Zorcery Cast or Defend] Draw a card and discard it after 10 seconds.",
    },
    {
        id: "Conjurer",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter] Conjure a zummon.\n[Defend] Gain 1 life.",
    },
    {
        id: "Zpellbook",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Draw a charm or zorcery.\n[Defend] Gain 1 life.",
    },
    {
        id: "Planar Warp",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nBanish an enchantment, zpell or zummon to the bottom of its owner's deck and draw a card.",
    },
    {
        id: "Ztudy",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\nZtudy takes 5 seconds longer to resolve for each mana consumed.\nConsume: Gain a zpell crystal.",
    },
    {
        id: "Trickster",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Attack] Draw a charm with mana cost 2 or less.",
    },
    {
        id: "Denied",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nCounter a zpell.\nIf there are no zummons in your arena, Denied's mana cost is 0.",
    },
    {
        id: "Grave Familiar",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Attack] Deal 2 damage.\nZacrifice: Gain 3 mana.",
    },
    {
        id: "Demonic Pact",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zacrifice] Gain life equal to the zacrifice's mana cost.",
    },
    {
        id: "Undertaker",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter] Bury 3 cards.\n[Exit] Bury 3 cards.",
    },
    {
        id: "Read the Entrails",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nZacrifice a zummon, draw 2 cards and gain a mana crystal.",
    },
    {
        id: "Last Gasp",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nResurrect a zummon.\nIt has a 10 second duration.",
    },
    {
        id: "Undeath",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nResurrect a zummon.\nIt gains: [Attack] Deal 2 damage.",
    },
    {
        id: "Immortality",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nA zummon gains: [Expiration] Resurrect this zummon.",
    },
    {
        id: "War's Toll",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nEach player buries 3 cards.\nResurrect an enchantment or zummon.",
    },
    {
        id: "Famine",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nEach player buries 3 cards.\nResurrect a zummon with mana cost 3 or less.",
    },
    {
        id: "Zhinigami",
        manaCost: 10,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Enchantment\n\n\n[Zummon Enter Void] Resurrect it.",
    },
    {
        id: "Vampire",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Zummon Enter] Deal 1 damage to each enemy and gain 1 life.",
    },
    {
        id: "Dhampir",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Zummon Exit] Deal 1 damage to each enemy and gain 1 life.",
    },
    {
        id: "Insatiable Greed",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[10 seconds] Draw a card and lose life equal to its mana cost.",
    },
    {
        id: "Price of Glory",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] Draw a card and bury cards equal to its mana cost.",
    },
    {
        id: "Hellraiser",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Resurrect an enchantment or zummon.\n[Attack] Deal 2 damage.",
    },
    {
        id: "Random Reaper",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Attack] Deal 2 damage.\nZacrifice: Each enemy zacrifices a random enchantment or zummon.",
    },
    {
        id: "Fell the Mighty",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nEach player zacrifices their zummon with the highest mana cost.",
    },
    {
        id: "Extinction",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\nDispel all auras, enchantments and zummons.\nEach player discards a random card.",
    },
    {
        id: "Ztitcher",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[10 seconds] If there are no Zombies in your arena, gain a Zombie.",
    },
    {
        id: "Cursed Zarcophagus",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] If you there are no Zombies in your arena, gain a Zombie.",
    },
    {
        id: "Zombie",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\n\[Attack] Deal 1 damage.",
    },
    {
        id: "Pandemic",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Enter] Gain a Zombie.\n[20 seconds] Gain a Zombie for each Zombie in your arena.",
    },
    {
        id: "Zinful Knowledge",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[30 seconds] Draw a card and lose 2 life.",
    },
    {
        id: "Blood Queen",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Gain a blood crystal\nBlood crystals deal double damage.",
    },
    {
        id: "Corpse Trader",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Zummon Exit] Gain a mana crystal.",
    },
    {
        id: "Collect Bounty",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDispel a zummon and gain mana crystals equal to its mana cost.",
    },
    {
        id: "Cult Leader",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter] Zacrifice a zummon and gain mana crystals equal to its mana cost.\n[Attack] Gain a blood crystal.",
    },
    {
        id: "Barrow Ghoul",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Attack] Each player draws a card.\n[Your Draw] Gain 2 life.\n[Enemy Draw] They lose 2 life.",
    },
    {
        id: "Zoul Devourer",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter] Intensity 3: Deal 1 damage to each enemy, then gain life equal to the total damage dealt.",
    },
    {
        id: "The Ravening",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nConsume: Deal 1 damage to each enemy, then gain life equal to the total damage dealt.",
    },
    {
        id: "Butcher",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Deal 3 damage.\n[Enter] Dispel an enchantment or zummon.",
    },
    {
        id: "Destiny Bonder",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Attack or Exit] Deal 2 damage to each enemy, then gain life equal to the total damage dealt.",
    },
    {
        id: "Massacre Beast",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter] Dispel all zummons with mana cost 3 or less. [Zummon Exit] Deal 2 damage to its controller.",
    },
    {
        id: "End of the Line",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nEach enemy zacrifices all auras, enchantments and zummons",
    },
    {
        id: "Cull",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nZacrifice a zummon and gain 4 mana.",
    },
    {
        id: "Fill the Cemetery",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nBury 3 zummons.",
    },
    {
        id: "Exterminate",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDispel an enchantment or zummon and bury 2 cards.",
    },
    {
        id: "Haunting Return",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nResurrect a zummon with mana cost 3 or less.",
    },
    {
        id: "Split in Two",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDispel your zummon and gain 2 copies of it.",
    },
    {
        id: "Bane",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nDispel a zummon.\nIf there are 7 or more zummons in the void, Bane's mana cost is 0.",
    },
    {
        id: "Zip and Zap",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDeal 1 damage.\n[Your Zorcery Cast] Reclaim Zip and Zap from the void.",
    },
    {
        id: "Avatar of Blood",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter and Attack] Gain 3 blood crystals.",
    },
    {
        id: "Magic Cannon",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter] Draw a card and deal damage to all enemies equal to its mana cost.\n[Attack] Deal 4 damage.",
    },
    {
        id: "Zpeed Zlinging",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nYour next zorcery resolves instantly.\nDraw a card.",
    },
    {
        id: "Ztitches in Time",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Enchantment\n\n\n\nYour zpells resolve instantly.",
    },
    {
        id: "Emergency Zummons",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\nYour zummons resolve instantly.",
    },
    {
        id: "Last Word",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nCounter all enemy zpells.",
    },
    {
        id: "Desperation",
        manaCost: 0,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nConsume: Counter a zpell.",
    },
    {
        id: "Outplay",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\Counter a zpell.\nDraw a card.",
    },
    {
        id: "Natural Resistances",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nCounter a charm or zorcery.",
    },
    {
        id: "Zerenity",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nCounter a zpell.\nIf you have an enchantment in your arena, Zerenity's mana cost is 0.",
    },
    {
        id: "Chaos Lord",
        manaCost: 8,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Attack] Conjure 1 from each player's deck.",
    },
    {
        id: "Dragon Zorcerer",
        manaCost: 8,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Deal 7 damage.\n[Ztrike] Dispel all zummons in the damaged enemy's arena.",
    },
    {
        id: "Lightning Vortex",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nConsume: Deal 1 damage and reduce the mana cost of your next zpell by 1.",
    },
    {
        id: "Catastrophe",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nConsume: Deal 1 damage to each player.",
    },
    {
        id: "Cataclysm",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\nConsume: Deal 1 damage to each player.\nDispel all zummons if 5 or more mana was consumed.",
    },
    {
        id: "Wrath",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDispel all zummons and each player loses life equal to the number of zummons they lost.",
    },
    {
        id: "Mimic",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nCopy a charm or zorcery.",
    },
    {
        id: "Double Down",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nReclaim a card.\nThe next time you cast the reclaimed card, copy it.",
    },
    {
        id: "Gamble",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDraw 3 cards, then discard 2 random cards.",
    },
    {
        id: "Zhadow Clones",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nCopy a zummon twice.\nThe copies have a duration of 10 seconds.",
    },
    {
        id: "Intense Glare",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n2 charges.\nAdd 1 intensity to all zummons in your arena.",
    },
    {
        id: "Gather Energy",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n\nGain 8 mana.",
    },
    {
        id: "Zupreme Zorcery",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\nDispel all non-zorcerer auras, enchantments and zummons.",
    },
    {
        id: "Zoul Harvest",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\nDispel all zummons and gain a life crystal for each one.",
    },
    {
        id: "Mass Zacrifice",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nEach player zacrifices all auras, enchantments and zummons in their arena.",
    },
    {
        id: "Crystal Mining",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nA zummon gains: [Attack] Gain 2 mana crystals.",
    },
    {
        id: "Muscle Up",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\nYour zummons gain: [Attack] Deal 1 damage.",
    },
    {
        id: "Earthwarden's Gift",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\nYour zummons gain: [Defend] Gain 2 life.",
    },
    {
        id: "Healing Wisdom",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] If you gained life in the last 10 seconds, draw a card.",
    },
    {
        id: "Pack Tactics",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] If there are 2 or more zummons in your arena, draw a card.",
    },
    {
        id: "Arcane Trader",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] If you cast 2 or more zpells in the last 10 seconds, gain 2 mana crystals.",
    },
    {
        id: "Gravekeeper",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] If you zacrificed a zummon in the last 10 seconds, each player buries 2 cards.",
    },
    {
        id: "Voidforge",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\nYou may cast zpells from the void.",
    },
    {
        id: "Common Ground",
        manaCost: 4,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Enchantment\n\[Your Zummon Enter] Gain 1 mana for each other zummon with the same zpell class in your arena.",
    },
    {
        id: "Zuicide Zquad",
        manaCost: 4,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Zummon\n\n\n\Your zummons cost 1 mana and have a 10 second duration.",
    },
    {
        id: "World Reflection",
        manaCost: 6,
        archetypes: [],
        tags: ["Build-around"],
        debugText: "Enchantment\n\n\n\nYour gains are doubled.",
    },
    {
        id: "Twice",
        manaCost: 5,
        archetypes: [],
        tags: ["Build-around"],
        debugText: "Enchantment\n\n\nYour zummon gains are doubled.",
    },
    {
        id: "Firebreather",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Deal 1 damage.\n[Your Zummon Cast] Deal 1 damage to each enemy.",
    },
    {
        id: "Zany Zapper",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\[Attack] Deal 1 damage.\n[Your Zorcery Cast] Deal 1 damage to each enemy.",
    },
    {
        id: "Ztatic Ztorm",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\[Attack] Deal 1 damage.\n[Your Charm Cast] Deal 1 damage to each enemy.",
    },
    {
        id: "Zecond Chance",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nReclaim a charm or zorcery from the void.",
    },
    {
        id: "Blood Diamond",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment - Curse\n\n[10 seconds] You and the cursed enemy gain a blood crystal.",
    },
    {
        id: "Crystallise",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment - Curse\n\n[10 seconds] You and the cursed enemy gain a mana crystal.",
    },
    {
        id: "Crazy Zorc",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Bury 2 zorceries.\n[Zpend 5 Mana] Reclaim a zorcery.",
    },
    {
        id: "Zpellzerker",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Attack] Intensity 1: Deal 1 damage.\n[Your Zorcery Cast] Increase Crazy Zorc's intensity by 1.",
    },
    {
        id: "Multiclass",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Attack] Deal 1 damage for each zpell class in your arena.",
    },
    {
        id: "Zpell Chain",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Your Charm Cast] Gain 1 mana.\n[Your Zorcery Cast] Gain 2 mana.",
    },
    {
        id: "Mana Fiend",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\n[Enter] Gain 5 mana.",
    },
    {
        id: "Lingering Rage",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Enter] Deal 5 damage.\nIf Lingering Rage is in the void, your zpells deal 1 extra damage.",
    },
    {
        id: "Zudden Ztrength",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nYour damage is doubled for 3 seconds.",
    },
    {
        id: "Mini Djinn",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter] Draw a zummon with mana cost 2 or less.",
    },
    {
        id: "Pyromaniac",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\[Attack] Deal 2 damage.\n[Ztrike] Draw a card.",
    },
    {
        id: "Zpell Zniper",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Charm or Zorcery Cast] Deal 2 damage.",
    },
    {
        id: "Wyldfyre",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nDispel all zummons.\nDeal 5 damage to each enemy.",
    },
    {
        id: "Armageddon",
        manaCost: 6,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nDispel all auras, enchantments and zummons.",
    },
    {
        id: "Happy Hour",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nReduce the mana cost of all your cards by 1.",
    },
    {
        id: "Fuel the Fire",
        manaCost: 4,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\nDispel a zummon.\nReduce the mana cost of your next zpell by 4.",
    },
    {
        id: "Power Zurge",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\nDeal 2 damage to each enemy.\nReduce the mana cost of your next zpell by 2.",
    },
    {
        id: "Elemental Horde",
        manaCost: 6,
        archetypes: [],
        tags: ["good"],
        debugText: "Enchantment\n[Your Zummon Enter] Deal 1 damage to each enemy.\n[30 seconds] Copy Elemental Horde.",
    },
    {
        id: "Time Jump",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n[Your Zummon Enter] Increase your timer zpeed by 100% for 15 seconds.",
    },
    {
        id: "Zpin to Win",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nDiscard your hand and draw 5 cards.",
    },
    {
        id: "Fresh Ztart",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nEach player discards their hand and draws 5 cards.",
    },
    {
        id: "Don't Get Greedy",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Enemy Draw] Deal 1 damage to that enemy.",
    },
    {
        id: "Even the Odds",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nEach player draws cards until they have the same number as the player who has the most.",
    },
    {
        id: "Lingering Fear",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Enter] Bury 6 cards.\nIf Lingering Fear is in the void, [Your Spell Cast] Each player buries a card.",
    },
    {
        id: "Longevity",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Enter] Reclaim a zummon.\nIf Longevity is in the void, your zummons last 100% longer.",
    },
    {
        id: "Primal Rage",
        manaCost: 4,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Zummon\nIntensity 3. If you would deal less damage than Primal Rage's intensity, deal damage equal to its intensity instead.",
    },
    {
        id: "Flamewrath",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter] Deal damage equal to Flamewrath's intensity. [Attack] Intensity 3: Deal 1 damage.",
    },
    {
        id: "Dark Harvest",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Enemy Dispel] You gain a blood crystal and a mana crystal.",
    },
    {
        id: "Mirror Universe",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\nGain 2 copies of an enchantment or zummon.",
    },
    {
        id: "Mirror Universe",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\nGain 2 copies of an enchantment or zummon.",
    },
    {
        id: "Blazing Imp",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Enter or Attack] Deal 4 damage.\nBlood crystals deal 1 extra damage.",
    },
    {
        id: "Miniature Zun",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Zummon\n[Attack All] Deal 1 damage.\n[Expiration] Gain mana equal to the life enemies lost in the last 10 seconds.",
    },
    {
        id: "Blitz Commander",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Zummon\n\n\n[Attack] Deal 2 damage.\nYour attacks are doubled.",
    },
    {
        id: "Propagandist",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Gain control of a zummon\n[Attack] Deal 2 damage.",
    },
    {
        id: "Lunar Blessing",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nAdd 3 intensity.",
    },
    {
        id: "Zolar Blessing",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nAdd 1 intensity to all your cards in your hand.\nReduce the mana cost of all cards in your hand by 1.",
    },
    {
        id: "Zpell Cascade",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\nGain 2 zpell crystals.\nAdd 2 mana if you have the most zummons in your arena.",
    },
    {
        id: "Fang Ztalker",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[15 seconds] Deal 2 damage.\n[Ztrike] Reclaim a random card.",
    },
    {
        id: "Void Zifter",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter] Intensity 1: Reclaim a random card.",
    },
    {
        id: "Reunion",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Zummon Cast] Gain a mana crystal.",
    },
    {
        id: "Zummer Chorus",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Zummon Cast] Gain a zpell crystal.",
    },
    {
        id: "Bird Zong",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nGain 10% mana regen.\nWhen you cast a zpell with mana cost 6 or more, reclaim Bird Song.",
    },
    {
        id: "Zoul Ziphon",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enemy Zpell Cast] Gain a mana crystal.",
    },
    {
        id: "Overgrowth",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter] For each enemy, dispel a random card.",
    },
    {
        id: "Aria of the Ancients",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Enter] Draw a card.\n[Your Enchantment Cast] Draw a card.",
    },
    {
        id: "Eyes of the Forest",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Your Zummon Damage] Draw a card.",
    },
    {
        id: "Blood for Blood",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zacrifice] Deal 1 damage to each enemy and gain 1 life.",
    },
    {
        id: "Profane Ritual",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Your Zacrifice] Draw a card and lose 2 life.",
    },
    {
        id: "Woodland Stomper",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Attack] Intensity 1: Deal 4 damage.",
    },
    {
        id: "Wildwood Elemental",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Attack All] Intensity 1: Deal 2 damage.",
    },
    {
        id: "Primal Behemoth",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Deal 4 damage.\n[Ztrike] Draw a card and gain 2 mana.",
    },
    {
        id: "Avatar of Life",
        manaCost: 8,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Attack] Deal 6 damage.\n[Ztrike] Reduce the mana cost of a random card in your hand to 0.",
    },
    {
        id: "Ritual of Renewal",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Your Zummon is Dispelled or Buried] Draw a card.",
    },
    {
        id: "Ztampede",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Your Zummon Cast] Add 1 intensity to Ztampede.\n[Your Zummon Cast] Intensity 2: Deal 1 damage.",
    },
    {
        id: "Wolf Pack",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Deal 1 damage to each enemy for each zummon in your arena.",
    },
    {
        id: "Animal Companions",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Draw a card for each druid zummon in your arena.\n[Attack] Deal 1 damage.",
    },
    {
        id: "Zong of Creation",
        manaCost: 4,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Enchantment\n\n\n[Your Zummon is Dispelled] Gain a Nature's Blessing.",
    },
    {
        id: "Bear Companion",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\nYour mana regen is increased by 20%.\n[Attack All] Deal 1 damage.",
    },
    {
        id: "Wandering Druid",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack All] Deal 1 damage.\n[Enter] Gain a Bear Companion",
    },
    {
        id: "Treefolk Elder",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Attack] Deal 4 damage.\n\n[Enter or Ztrike] Gain 20% mana regen.",
    },
    {
        id: "Progenitor",
        manaCost: 10,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Deal 7 damage.\n[Ztrike] Gain a mana crystal for each damage dealt.",
    },
    {
        id: "Mind Reading",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment - Curse\n\n\n[Cursed Enemy Draw] Draw a card.",
    },
    {
        id: "Hungry Zlime",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Dispel an aura or enchantment and gain life equal to its mana cost.",
    },
    {
        id: "Pull from the Ether",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nDraw an enchantment card.",
    },
    {
        id: "Giant Zummoning",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDraw a zummon card with mana cost 6 or more.",
    },
    {
        id: "Zow the Land",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nConsume: Gain 10% mana regen.",
    },
    {
        id: "Circle of Life",
        manaCost: 1,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nZacrifice a zummon and draw cards equal to its mana cost.",
    },
    {
        id: "Food Chain",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n2 charges.\nZacrifice a zummon and gain a random zummon from your deck with a higher mana cost.",
    },
    {
        id: "Zeason of Growth",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\nEach enemy gains 10% mana regen.\nGain 40% mana regen.",
    },
    {
        id: "Life Force",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nDraw a card for each zummon in your arena and gain life equal to their mana costs.",
    },
    {
        id: "Wild Zummoning",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDraw 2 zummon cards.\nReduce the mana cost of your next zummon zpell by 6.",
    },
    {
        id: "Birthing Pool",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n\nZummons cost 1 less to cast.",
    },
    {
        id: "Everglades",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Enchantment\n\n[Your Zummon Cast] Reduce the mana cost of your next enchantment zpell to 0.",
    },
    {
        id: "Nature's Revenge",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Your Zummon is Dispelled] Gain 2 random zummons from your deck and zacrifice Nature's Revenge.",
    },
    {
        id: "Zpring Bloom",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n\nGain 20% mana regen.",
    },
    {
        id: "Forest Dryad",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\n[10 seconds] Gain 1 mana.",
    },
    {
        id: "Harvest",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\n\nGain 3 mana crystals.",
    },
    {
        id: "Midsummer Festival",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Enchantment\n\n\n[10 seconds] Gain 1 mana for each zpell class in your arena.",
    },
    {
        id: "Insatiable Zapling",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\n\n\n[Enter] Dispel an aura or enchantment.",
    },
    {
        id: "Mana Zurge",
        manaCost: 0,
        archetypes: [],
        tags: [],
        debugText: "Charm\n\n\n\nGain 2 mana.",
    },
    {
        id: "The World Tree",
        manaCost: 10,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\n\n\nYour mana gain is tripled.",
    },
    {
        id: "Nature's Blessing",
        manaCost: 3,
        archetypes: [],
        tags: [],
        debugText: "Enchantment\n\n\nYour mana regen is increased by 30%.",
    },
    {
        id: "Eternity",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Aura\n\n\nYour zummons do not expire.\nChannel 1.",
    },
    {
        id: "Counterzpell",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\n\nCounter a zpell.",
    },
    {
        id: "Epiphany",
        manaCost: 4,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n\nDraw 3 cards.",
    },
    {
        id: "Will-o'-Wisp",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Banish an enchantment or zummon to the top of its owner's deck.",
    },
    {
        id: "Inspiration",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\n\n\n\n[Enemy Draw] Draw a card.",
    },
    {
        id: "Deja Vu",
        manaCost: 5,
        archetypes: [],
        tags: [],
        debugText: "Enchantment\n\n\n\nYour triggers are doubled.",
    },
    {
        id: "Poke and Prod",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDeal 1 damage.\n3 Charges.",
    },
    {
        id: "Zcorched Earth",
        manaCost: 10,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\n\n\nYour damage dealt is tripled.",
    },
    {
        id: "Zpellstone",
        manaCost: 3,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\n\nYour charms and zorceries deal 1 extra damage.",
    },
    {
        id: "Flame Zpirit",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Zpell Cast] Deal 1 damage.",
    },
    {
        id: "Reflection",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n\nCopy a zummon.",
    },
    {
        id: "Fae Mischief",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n[Enter] Take control of an enchantment or zummon.",
    },
    {
        id: "Evil Twin",
        manaCost: 5,
        archetypes: [],
        tags: [],
        debugText: "Zorcery\n\n\n\nDispel a zummon and copy it.",
    },
    {
        id: "Zpellsteal",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\n\nCounter a zpell, then reclaim it.",
    },
    {
        id: "Forbidden Rites",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nResurrect an enchantment or zummon.",
    },
    {
        id: "Traumatic End",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\nDispel a zummon and each player buries 3 cards.",
    },
    {
        id: "Grave Echoes",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zummon Exits] Deal 1 damage to each enemy and you gain 1 life.",
    },
    {
        id: "Drain Life",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\nDispel a zummon and gain life crystals equal to its mana cost.",
    },
    {
        id: "Fiery Zpirit",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zpell Cast] Add 1 intensity to all cards in your hand.",
    },
    {
        id: "Wild Growth",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[10 seconds] Gain 1 mana.\nYou may cast this card from the void.",
    },
    {
        id: "Zpirit of the Woods",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[Attack] Intensity 1: Gain 1 Mana.",
    },
    {
        id: "Mystic Glade",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] Your mana regen is increased by 15% for each enchantment in your arena.",
    },
    {
        id: "Mana Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\nZacrifice: Gain 1 mana.",
    },
    {
        id: "Life Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\nZacrifice: Gain 2 life.",
    },
    {
        id: "Zpell Crystal",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n\nZacrifice: Draw a card.",
    },
    {
        id: "Blood Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\nZacrifice: deal 1 damage to each enemy.",
    },
    {
        id: "Berserker Chieftain",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[10 seconds] Add 1 intensity to all zummons in your arena.\n[Attack] Intensity 1: Deal 1 damage.",
    },
    {
        id: "Jack of All Trades",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Aura\n\nZpells you cast are every zpell class.\nChannel 1.",
    },
    {
        id: "Void Zalvager",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\n\n\n\n[Enter] Reclaim a card.",
    },
    {
        id: "Chaining Ztorm",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zpell Cast] Add 1 intensity to all cards in your arena.",
    },
    {
        id: "Enchantress",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter] Draw a random enchantment card from your deck.",
    },
    {
        id: "Call of the Abyss",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n\n[30 seconds] Reclaim a random zummon.",
    },
    {
        id: "Zhocking Impact",
        manaCost: 5,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Your Zummon Enter] Deal damage equal to the its mana cost.",
    },
    {
        id: "Fire Drake",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Attack] Deal 4 damage.\n[Your Zummon Enter] Deal damage equal to its mana cost.",
    },
    {
        id: "Zorcerous Twin",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Your Charm or Zorcery Cast] Copy it.",
    },
    {
        id: "Zpellstorm",
        manaCost: 8,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Enter] Conjure 2. \n[Your Zpell Cast] Deal damage equal to its mana cost.",
    },
    {
        id: "Uniformity",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nEach zummon becomes a copy of a zummon.",
    },
    {
        id: "Reality Warp",
        manaCost: 8,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nBanish all enemy auras, enchantments, zpells and zummons to their hand.",
    },
    {
        id: "Lingering Presence",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\nZacrifice a zummon and conjure an enchantment from your deck.",
    },
    {
        id: "Hypersense",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Enchantment\n[Your Non-Zummon Cast] Trigger a random enchantment or zummon in your arena.",
    },
    {
        id: "Deflector Mage",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\nZummons cannot attack you.\n[Defend] Gain 1 life.",
    },
    {
        id: "Master of Arcana",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\nTrace a charm or zorcery.\n[Enter] Gain a copy of the traced card. Its mana cost is 0.",
    },
    {
        id: "Master of the Arena",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\nTrace an enchantment or zummon.\n[Enter] Gain a copy of the traced card. It's mana cost is 0.",
    },
    {
        id: "Voidling",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\nVoidling resolves instantly.\n[Enter]: Cast a zpell from the void without paying mana. It resolves instantly.",
    },
    {
        id: "Dominator",
        manaCost: 7,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\n[Enter]: Gain control of an aura, enchantment or zummon.",
    },
    {
        id: "Facets",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[Enter] Gain a zpell crystal.\nYour crystals gain: Your mana regen is increased by 10%.",
    },
    {
        id: "Red Portal",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[5 seconds] Conjure the top card of your deck if it is a charm or zorcery.",
    },
    {
        id: "Green Portal",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[5 seconds] Conjure the top card of your deck if it is an enchantment or zummon.",
    },
    {
        id: "Recycle",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nBanish your hand to your deck and draw that many cards.",
    },
    {
        id: "Academy Zentinel",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n[Attack] Gain a shield\n[Exit] Trigger all enchantments and zummons in your arena.",
    },
    {
        id: "Intense Training",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nTrigger an enchantment or zummon.\nIt gains: [Attack] Draw a card.",
    },
    {
        id: "Zecret Ztash",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nChoose a card, draw 2 cards, then banish the chosen card to the top of your deck.",
    },
    {
        id: "Delay",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nBanish an enchantment or zummon to the top of its owner's deck.\nGain 3 mana crystals.",
    },
    {
        id: "Discombobulate",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\n\nCounter a non-zummon zpell.",
    },
    {
        id: "Vex",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nCounter an enchantment or zummon zpell.",
    },
    {
        id: "Bribery",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nCounter a zpell.\nIt's controller gains 3 mana crystals.",
    },
    {
        id: "Trap in Crystal",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nCounter a zpell.\nBoth you and the zpell's controller gain a zpell crystal.",
    },
    {
        id: "Hijack",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nCounter a zpell, then reclaim it. Its mana cost is 0.",
    },
    {
        id: "Void Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\nZacrifice: Each player buries a card.",
    },
    {
        id: "Time Crystal",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n\nZacrifice: Increase your timer zpeed by 10% for 30 seconds.",
    },
    {
        id: "Time Fracture",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n\nGain 3 time crystals.",
    },
    {
        id: "Voidminer",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\n\n[Enter or Attack] Gain a void crystal\n[Defend] Gain 1 life.",
    },
    {
        id: "Whirling Thoughts",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDraw 4 cards, then discard 2 random cards.",
    },
    {
        id: "Ultimate Defence",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Charm\nGain 2 zhields.\nEach aura, enchantment and zummon in your arena gains a zhield.",
    },
    {
        id: "Zhroud of Mystery",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\nDraw a card.\nZummons in your arena have ztealth.",
    },
    {
        id: "Zelf Reflection",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\nGain 4 life.\nCopy an enchantment or zummon. If you have the most life, copy it twice.",
    },
    {
        id: "Expose",
        manaCost: 0,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDraw a card.\nEnemies reveal their hands for 30 seconds.",
    },
    {
        id: "Mind Roil",
        manaCost: 1,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\n\nDraw a card.\nEach player buries 3 cards.",
    },
    {
        id: "Zombie Apocalypse",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n\nEcho: Gain a Zombie.",
    },
    {
        id: "Brain Trust",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n\nEcho: Gain a zpell crystal.",
    },
    {
        id: "Acceleration",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n\nEcho: Gain a time crystal.",
    },
    {
        id: "Crimson Carpet",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\n\nEcho: Gain a blood crystal.",
    },
    {
        id: "Mana Nexus",
        manaCost: 5,
        archetypes: [],
        tags: ["build-around"],
        debugText: "Aura\n\n\n\nAuras have no channel cost.",
    },
    {
        id: "Fate Zpinning",
        manaCost: 6,
        archetypes: [],
        tags: [""],
        debugText: "Zorcery\n\n\nDiscard your hand, draw 5 cards and gain 5 mana.",
    },
    {
        id: "Tax Wizard",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\nZhield 1.\nYour zpells cost 1 less to cast.\nEnemy zpells cost 1 more to cast.",
    },
    {
        id: "Den of Evil",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n\n[10 seconds] Deal 2 damage to each player and each player draws a card.",
    },
];
cardIds = cards.map(card => card.id);
cardsById = cards.reduce(
    (dictionary, card) => {
        dictionary[card.id] = card;
        return dictionary;
    }, {}
);