cards = [
    {
        id: "Zpring Bloom",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\n+20% mana regen.",
    },
    {
        id: "Mana Zurge",
        manaCost: 0,
        archetypes: [],
        tags: [],
        debugText: "Charm\n\n\n+2 mana.",
    },
    {
        id: "The World Tree",
        manaCost: 10,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\n\n+200% mana regen.",
    },
    {
        id: "Nature's Blessing",
        manaCost: 3,
        archetypes: [],
        tags: [],
        debugText: "Enchantment\n\n\n+30% mana regen.",
    },
    {
        id: "Counterzpell",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\n\nCounter a zpell.",
    },
    {
        id: "Epiphany",
        manaCost: 4,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nDraw 3 cards.",
    },
    {
        id: "Will-o'-Wisp",
        manaCost: 4,
        archetypes: [],
        tags: [""],
        debugText: "Zummon\nEnter: Banish an enchantment or zummon to the top of its owner's deck.",
    },
    {
        id: "Inspiration",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\n\n[Opponent's Draw] Draw a card.",
    },
    {
        id: "Deja Vu",
        manaCost: 5,
        archetypes: [],
        tags: [],
        debugText: "Enchantment\n\nDouble all your triggers.",
    },
    {
        id: "Poke and Prod",
        manaCost: 2,
        archetypes: [],
        tags: [""],
        debugText: "Charm\n\nDeal 1 damage.\n3 Charges.",
    },
    {
        id: "Zcorched Earth",
        manaCost: 10,
        archetypes: [],
        tags: [],
        debugText: "Zummon\n\nTriple all damage you deal.",
    },
    {
        id: "Zpellstone",
        manaCost: 3,
        archetypes: [],
        tags: [],
        debugText: "Zummon\nYour charms and sorceries deal 1 extra damage.",
    },
    {
        id: "Flame Zpirit",
        manaCost: 3,
        archetypes: [13, 14, 15],
        tags: [""],
        debugText: "Zummon\n\n[Your Spell Cast] Deal 1 damage.",
    },
    {
        id: "Reflection",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\n\n\nCopy a zummon.",
    },
    {
        id: "Fae Mischief",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Zorcery\nEnter: Take control of an enchantment or zummon",
    },
    {
        id: "Evil Twin",
        manaCost: 5,
        archetypes: [],
        tags: [],
        debugText: "Zorcery\n\nDispel a zummon and copy it.",
    },
    {
        id: "Zpellsteal",
        manaCost: 5,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\n\nCounter a spell and put it into your hand.",
    },
    {
        id: "Forbidden Rites",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Zummon\nReturn an enchantment or zummon from a graveyard to your board.",
    },
    {
        id: "Traumatic End",
        manaCost: 2,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\nDispel a zummon and each player scraps 3 cards.",
    },
    {
        id: "Grave Echoes",
        manaCost: 3,
        archetypes: [],
        tags: [""],
        debugText: "Enchantment\n[Your Zummon Exits] Deal 1 damage to each opponent and you gain 1 life.",
    },
    {
        id: "Drain Life",
        manaCost: 3,
        archetypes: [],
        tags: ["good"],
        debugText: "Charm\nDispel a zummon and gain life crystals equal to its mana cost.",
    },
];
cardIds = cards.map(card => card.id);
cardsById = cards.reduce(
    (dictionary, card) => {
        dictionary[card.id] = card;
        return dictionary;
    }, {}
);